### ISSUE TITLE
finalize o.points.phase~ into one object

### ISSUE THREAD

**Issue by kulpajj** [CNMAT/Music-and-Computing#78]
Rename o.points.buffer~ to be the one and only o.points.phase~ upon the next release.

**Comment by ramagottfried** [comment]
cool, are you ready to do this for the class?

Ed and I were talking about renaming all the m158. to be cnmat. also, would that be problematic?  I'm assuming yes.

**Comment by ramagottfried** [comment]
ok I'm just about to push points.buffer~ converted to points.phase~ to the repository.

@kulpajj question: should it actually be called phase.points?  we input phase and get out the points, so maybe that makes more sense no?

**Comment by ramagottfried** [comment]
for what it's worth, the gen~ abstraction is called phase.points, which is kind of in keeping with the naming scheme:

phase~
phase.click~
phase.points~

looks better to me I think

**Comment by ramagottfried** [comment]
ok, I did that : )

**Comment by kulpajj** [comment]
sure!  Then it's named as a consistent library.

**Comment by kulpajj** [comment]
sure!  Then it's named as a consistent library. (I really have to start
replying to all, sorry).

**Comment by equilet** [comment]
second for phase.points~

**Comment by ramagottfried** [comment]
great, I just pushed it to the repo! 👍

**Comment by ramagottfried** [comment]
ok done, closing
p.s. I also renamed everything to be cnmat. instead of m158. in preparation for eventual release.
