### ISSUE TITLE
filename symbols can not check out on windows

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/Music-and-Computing#82]
Getting this on a Windows checkout:

```
Receiving objects: 100% (612/612), 73.64 MiB | 17.34 MiB/s, done.
Resolving deltas: 100% (351/351), done.
error: unable to create file help/o.expr-helpers/odot-<.maxhelp: Invalid argument
error: unable to create file help/o.expr-helpers/odot-<=.maxhelp: Invalid argument
error: unable to create file help/o.expr-helpers/odot->.maxhelp: Invalid argument
error: unable to create file help/o.expr-helpers/odot->=.maxhelp: Invalid argument
error: unable to create file help/o.expr-helpers/odot-??=.maxhelp: Invalid argument
error: unable to create file help/o.expr-helpers/odot-||.maxhelp: Invalid argument
fatal: cannot create directory at 'patchers/course/dev/o.*~_dev': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Also, these look like Haskell's monad syntax, which I approve of tremendously -- https://www.haskell.org/tutorial/monads.html

Love you all.

**Comment by ramagottfried** [comment]
hi @ilzxc !
thanks!

I'm guessing that's a windows file name limitation issue... do you know if that's the case off the top of your head? I could google of course : )

**Comment by ramagottfried** [comment]
p.s. @ilzxc the update is going to break all your patches! so maybe save a back up version of the older release.  We changed the names to be cnmat. instead of m158. and m158.o.points.buffer~ is now cnmat.o.phase.points~

**Comment by ramagottfried** [comment]
yep: https://support.microsoft.com/en-us/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names--fo

**Comment by ilzxc** [comment]
Whether or not you want to worry about Windows is completely up to you, just a heads up. (This won’t go away, so if you want Windows support — leq, less, geq, greater, and whatever the right name for ??= is.)

PS odot runs well in x64, but that’s for a different thread.

**Comment by ramagottfried** [comment]
working on fixing this as we speak, ... calling ??= "init" for now.

great to hear about x64!

**Comment by ramagottfried** [comment]
ok just pushed, let me know if that fixes it

**Comment by ilzxc** [comment]
Almost -- `fatal: cannot create directory at 'patchers/course/dev/o.*~_dev': Invalid argument`

**Comment by equilet** [comment]
> calling ??= "init" for now.

how about ncao?

**Comment by ramagottfried** [comment]
thanks @ilzxc, fixed, does it work now?

@equilet just to make you happy I changed the name to odot-null_coalescing_operator.maxhelp : )

**Comment by ilzxc** [comment]
This is now resolved, thanks ;)
