### ISSUE TITLE
cnmat.o.click.counter~ not counting

### ISSUE THREAD

**Issue by equilet** [CNMAT/Music-and-Computing#84]
I have the following code that I essentially copied from an example file

<pre><code>
----------begin_max5_patcher----------
822.3oc4XErbaBCD8L9qfgyDhj.rgdqeGsYxHiUbHEjX.QpSyj7sWoUfiqMX
HAbygLSFovhjd58zxtq7yKrbVK1wpbr+l8OrsrddgkEXRavp4YKmb5tjLZEL
Lm00Rof63ZdU5FvnX8CW42ZqR9TFCL2ZgWmmxyXRXEvuYTTKO1pwj7oBlYS4
rlx25XeSyqKnxj6S4ausjkHMi.6G5gba6HAss12nmxKKVnabGI6RD44Ltrci
KY6.TbJYULYGjFSlDqQ8SqfPjlIA.q7WArB8AYkvSwqBQE6DdccdkpKDgb+I
+5DQMWpdb+IYVJmAF0ikbJ6IAGtfIhLQoYyi7vQQtG0g069tzl1U9NAWdGMg
cnxnsUk9GvFl3gdeNOm0wgD.JrOzhCIvCQGrIqnOx1b65Z9lL1sYL9V485YF
R558anRpYc8Ccsi07EuR2nWbDznsgvJ8XD+gIpyd87Qw5EIDLFDnMDdzHcsu
RO52LrzL0XXl3+YineGp+0Rq.eHOLN62JGhSbuR34TomvScb8psxWqiufHSK
tgeeG8Uoa4zLG2lHHtiyYH13LfgNB4C981YUih6oUrW6RIFarDRmJQvvJQW+
2XTELA5hVNIUo2LGD7mTpi.xAwXmXli9NyyRS9UWm133KCoaNYGAsWAzN.OM
W8570rxNI3RmChgyo4FN98xTsiWC0S2BA62GWejd9uiLE4hMr9+ngL7GM2kI
nxyqmlT09lLIwWLAc0WEA0uopmKsfF8UQPaK0YdDzymqGh34AkMpjcaSUkco
9giL.n++6zcj.eHq2xokuqJQTzYh9nIkm+L2YvDQmPHlKDg12cgphwq2raK+
zRt0VxRXSkb9cdFBq.b+lit7KrhZ6+qvTIpKSZ2Esdu1j8ajMrJYJmJSUE3b
vfTxfceh+6BI7PHsZtPBMDRQyARwiAoFhOIjz0VNLRwy.mzkuOHRygCg9FSC
6503eNcjFhRs7d5HMjSt+b.TvXnzbfzxw5h+1fDkaXvufB5hibT2.iOIFIsn
3QVYUyrALUoIdv7K8rxEdLkadDxT6TxdLsc7PVZGZoJJsTEhttzjKXWjIAAT
6SIuNsAaExur3u.Ms4pk
-----------end_max5_patcher-----------
</code></pre>

For some reason, it's not counting.  Can you tell me why?
Does it work on your machine?

**Comment by equilet** [comment]
caveat:  the 3rd outlet (which should be labeled "carry count") does seem to function

**Comment by ramagottfried** [comment]
hi @equilet -- weird, looks like it's something to do with number~ display refresh (a GUI problem as usual! ;-)

hooking a minmax~ up to the output exposes the count (see below) I'll add one in the help patch, thanks.

<pre><code>
----------begin_max5_patcher----------
947.3oc2XE0aaBCD94jeEHdllZafPXuseGaUUND2T5.aDX5RWU6u8YeFRXMP
BowosZRQlvgsu666Ne2AOOch6RwFVkqy2b9gyjIOOcxDPjVvjl6m3lS2jjQq
fo4lyppnqYtdlmIYajf7RVES1JkWmKpkYLIrFbizJ4SYLXxsyqfJStOku91R
VhzXE9AjYHOG+EvkPjdjn9uyMMqwrwxmJXlE35t8QoqfcWr7gqh5XJo7VKgn
k8xzo5AuQBX0FrjU9Z+PiLHztSvk2QS.gnggKFGqQX.JReIFuGbyEqXc0jde
qR+CHCq4nAXkpz0bZlqmi6cYBprWRJnqwxo4FD78xT8B6i9ZQa5Z.Va0dg16
ykTYpfOH3PMCN27kyKPHFCEHzOZu.4B6EH9HC3hOeu.62JKduy9JiSMsAbNA
mxoebrOb5OBrULZDG+2QwukrOHqisVBhk0RofagTeX+P.0lKjf1wgw9RJecu
nyuWzgeGnKQjmqBpNk78nSAzAlT7AgF+NfYTGL20kQrFpDyT3pPTsecrqyqT
WBQHuexuNQTykpa2RmYobFHr6Aw9c4iM0S.feyYTbXSwuNDvXS0zetkfCmBg
9Ha0sKq4qxX2lw3qk2qebXuOeEURapQGpRRtPYt3H8f4jpdPKCgU4WFwOLQ4
00qGEq2jPPXPfVP3alomyU5YuSvbyRigUh+GCQ+Lzv6klcsYpuDUlO4LwLE8
9piJ1o+SD9mxIhlHhXSDA9jRABID7FJXvdYENHaTbOshYipAMLAl.WVL+8UL
X2+5mUHe8pDDP5jT7rJDPvWbedVZxud0dfNJzzsxnc18VpH1dv9h14YS4OeS
9+O3NOwyO6VO+xQn9McR74PnQ++QnsMn74PnK9THzCWqGx3MCZCTQ6NltDsW
4NR.7NP34Wl5c3vdIN+2AOUkHJFpP+I8R.lb9DBw79OnsW5C.Kr2m14ncwLy
ZU2Z6kIrosN+yp917iVdCVE79Ju4y6A1lV9+RLUh5xjVM2VB0Ym0shUIS4v2
Vn6jTASN3AZndrZJZLJxLmyROXisdP8PrjdNFdBrgdBGOw0FiUthUNbmPiUy
yGanQOZFcVZV+NLNjwnZxGB6t3R.x1SUGV0Q1JD5nz4bKnowDxr3RDqRBFgl
gvpyEhvlbL2l0TzQgjMRk0tIGTS1H7fLljlskj1qLGsn3QVYUyrAknpz+f.B
eh7faS4laguEiaI6wz14CMo4RKUkrkp500klh4ala93YPCtk75zlXQkleY5e
ADcay3I
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
aha!
