### ISSUE TITLE
cnmat.o.phase.points~ issue 

### ISSUE THREAD

**Issue by dappertutto** [CNMAT/Music-and-Computing#92]
I've isolated the problem in the patch copied below. Make sure audio is on, and click the o.compose.

<pre><code>
----------begin_max5_patcher----------
2371.3oc6c0zbiaiD8r8uBU7rrF.PPPx81jK6dYygrm1Z1obQSQqgITjpHob
rSpje6K9fTCkrrkjsrFV0qilHICR.z8CMa75FfT+40W4cW0iYMdS9GS9xjqt
5Ou9pqrEYJ3pt+9JukIOlVjzXOMupYyyaVUj7j2T2Qaydr0djOsrQ+AmwXS+
ekeZUUdYaymdzzzrYSmvlEXdK9qCN3StC5OcB2cFesuQKxKyRqVWZaY+tBKW
uLurHq0JH7AceZUQUsSI3yXS29sIe86UuZc6t0+9px16SRyLkw5JaURa52xK
WbacVZqqc8CBLsmPJrevklOTCadSC0j+G1FhaNKWwttr8oUYtFxyaSMxm6Pz
690aB8LE8WWes4soG4PQ1eLOI8u81G5H5Jro8oBaG64sWT30zXkUSE9VbTo1
7w9je+2h7WMKsZ4pplrevlRh8aJwlwihltyGmMCJAyZBIhbnr05J3rYOEDzq
9MIOjM+16VWNuH61hrxEsey0hQ66DlmzlzavOcRrQg4gl2LC9L6alxXbMfbD
+iKlNQZpOK1zHA1BkRSAAael5AtaDxAEXNKaUMsAmy6piSR3ptlydFB1N0qS
R6e6X9mxH.9hW7Pl93l.wK8F+MJ47iWxshgLvXkr++2dBl1+DztIe8MbcaSZ
0prW2uy8K15BoXEKLxL5NKRDJsn0LdfJR4u8UTKpymuUEMx3l2FdloIEoatp
V3+9c20e8nyAOWZ82EFLnKqSJWjMPv362UHm0222sMHvhCjQNUmw7iUceSD2
CBugghxreW2mOy+YZ4xj1YUyV8sjlrYNWj+8jNek6cf6XQP0AQPdL23elGxb
d1FfROy2US9hxjBuoG+21q2tXOxJd3j1bQncHvMocj5zMhUiEaXqE76iii7v
lrN7JR8dsX2q0ojrN2lRYz.Fkujw4MVRdRMCvWvK63wIaZQd5uo8ttb+dV4G
ItINnYZTrE3NMGq60jTLzjzdBVZx6DHnURLkuM1zTstNsuibslVp1zMyyZZy
KSZyqJGbNw5yQ7Bn+w1Ol1H3.8Sn2Kyp4T5G1A5Gyr7u6NxvR+f8j3LzQxin
e1VqqpmmYunh8g2wp82w72UGKNhNV9QnwGSGyOrF6tnLY0pGxpa5pssO0tl9
Um6tvo1+Luz8mV+yd0YOj2e91I97Rp0tSZ09RVW6b+7nR54pZktiKWm202Zs
85N2T63HnLYoqped877p+SaR65la+2YkqcdxzZ48IqKZ2FYtaw84EEabNe0l
incg14nxyczocEukibQrjyswc6y8CEVG495uDDLvYSWc38URFHiYlvblIUlI
AseKR3G3amdampI9dew3toJ7YwQLo6a5h3aMgnFKKW37gKrNg6JcUc0pp59w
XcUi2b9qaqVTmLOOyMIp0zxMD6faqgUs9n6N6f2RMfl2WmgFhaFLta8c2UjM
wNezqLNLLOBewlIgsRwPeyoMM+bctdNidWMuSoKMYkAQNJwqOcIewLEwz8J1
Cl69cJXYkOjUnIWc6RYw609cyX69MG8CUxPKYD+HoO2ZWI2wj5MZIty0JmY6
2yoYZdYSa85z1I+V1SuFd+rruIT7H2EyJoJLzpUp.lhsCg18YEO4mpJletLk
2nA14.NIcHT6GxQGUxhYtuEF5KXxmqCe+p.9YRvcDW+uYEEU+dOi48K3Ioo5
tXKQORDXR8mVdi3NAmEnIWG7bAeauKAwLVz4RAVu7tr5e5jkcFmGprd+8sgE
YUi.yTJaEEvYQ59mmtzYSPsu4+rgmniQSDd9Ere4jErvMdo3x.VrE1X5YOEw
mSoqQyEwLyv77Gx0DPZN9YG7eIytfKzjZ8hdd48USxVt5zbFHDAQw1gbsWLk
Cn0lowR+C3LX5oNS9+Jq3gr17zjI+b15rOLs+0Mv9Ap+erC52vGsJ9EafeDi
Ae7C9jAPOJ.tQ.YHLDIHiAA5.fO5.fDc.H.c.PgM..tKPvc.JI1PiZufWZbP
Q3f8UHgC1WQDNXdwfdVBrCSDaBRXyOB6nCkTxx5ABAADNfvm.BGPPQN0ADTn
Sc.AE6j8EYOXegcZECgV6ifV6iQV6IhhVT.6kVV.c9hnPDrn.1WB.clSfdM0
gl3Kz7dgl1KxrdYzL9i2UI6hBBT3Oi30L6hBBT9wobgNtyD5EEDnMTzHNunW
VP.5DCDA8FNNB58abDzYEJB5zBEAcdg.N4..6tWP4EQCBTdQzf.kWDMHP4EQ
CBTdQf9ltCXFv.S+EXtuJ5lHvgBHm1GE8nWY.RPjAc3.wGzgCDkPGNPqVlCG
nELyfCjWRCJP9HMnfDYpSHG2D1QNEhrxC7tIE3w8PJJQr2I0QjAvHd2jeAw.
buG5vMQg3tYAvcIwvM1NbCrC2n5vkZOtbZIJsi5M98EEDn74Nh2F3WTPfVsq
Q7lB+BBBTn9zDC.+7RRPaLndT.bi.xPXCRPdDEziRrA3.QXVP+LsL.GHZyBx
KYGJP9HEHee0HP9NqQf78Vi.4cJj.4cIifdj6YAAJbQA8H2yBBDIHA8H2yAB
PmEMItOuUDi4edptLZuDZsO.ZsG4vfPdjmREnfd5pZAA5oqpf1MEFP.XJfBZ
IjMn.kcHAxgB3SWEnQAJcHBZAy0X.wPVbCQPVbCwOVP2Ww.+ayo.2DiiaDQ3
xBF1jgSqEJw7m38Sr9U3tR3J5dIYz+TW9hXDHPV48QV4kHq7AHq7JbUdfc2A
ryNJbGEEvyH9Yk7kDCnE5PQKzAYELheNJ+gOgHY9C7Ow3n9KsK763K3S2G72
GfvutWvGGH7AABeDfvS7GdxuvuC2hgk7eLr4+NF1zeGC6B8EC6p7Ei5R7Ap6
M5l5Sf693QPOXf+NJfsQf.Yk2GYkWhrxGfrxqvU4A1cGvN6jDSG32LWB59WY
T+zM9RhAQDFvfc1.bC2CWxO3x8A2n7jTBtFyO6hunffOABRJJnw7Cz3KJHPw
AwI6.NtoALDVMOBVMOFUMmH.JvcIdEvlmGhxuOtl8vl0CXWWaXIyBKWVXoxh
JSVTox.eZrgOBF34xBepqQOckft.tfFGCnQw.ZLLfFASH76OgPbu4aBo6.qN
TPPX.74pNj1i9VLHfv.32aJgjGQxeHpA9EhZnegvF7Gtg+A5BXgpZCezdftt
kwHOvWms30T9ePCRs4sEYMGRvNL3JXeDBrtN+00+ehqC3kC
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
I personally cannot reproduce this, but it doesn't mean there isn't something fishy going on in your system @dappertutto.  If you get a chance, please take a minute to to to `Max -> About Max` and click "copy support information to clipboard", then paste it here.  Thank you!

**Comment by equilet** [comment]
Spoke with dappertutto and it looks like it was an issue with the version of packages on his system.
