### ISSUE TITLE
renaming folder Music-and-Computing (not Music-and-Computing-1.7)

### ISSUE THREAD

**Issue by dappertutto** [CNMAT/Music-and-Computing#93]
This is needed in order for media to be found automatically in the course materials. 

E.g., when opening 04_time_and_buffers I get error in Max Console: "folder: ~/Documents/Max 7/Packages/Music-and-Computing/media/808/: not a folder"

**Comment by equilet** [comment]
I fixed this in the release - now the download is: 
https://github.com/CNMAT/Music-and-Computing/releases/download/1.7/Music-and-Computing.zip
